before_script:
  # 登录到 docker hub
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t vertx-ddns:debian .
  - docker push "$DOCKER_USERNAME"/vertx-ddns:debian

