common:
  serverPort: 8080
  ipApiList:
    - https://api-ipv4.ip.sb/ip
    - https://jsonip.com/
    - https://myip.ipip.net
    - https://ddns.oray.com/checkip
aliyun:
  accessKeyId: LTAI5tDQhy5qHf9AvJocLX7G
  secret: RzGsKDseCshfB9MS3u7d46o7zLNWik
  defaultRegionId: cn-shenzhen  #默认地域id
  regionIdList: #阿里云所有地域id集合
    - cn-hangzhou #华东1（杭州）
    - cn-shanghai #华东2（上海）
    - cn-qingdao  #华北1（青岛）
    - cn-beijing  #华北2（北京）
    - cn-zhangjiakou  #华北3（张家口）
    - cn-huhehaote  #华北5（呼和浩特）
    - cn-shenzhen #华南1（深圳）
    - cn-heyuan #华南2（河源）
    - cn-chengdu  #西南1（成都）
    - cn-hongkong #中国（香港）
    - ap-northeast-1  #日本（东京）
    - ap-south-1  #印度（孟买）
    - ap-southeast-1  #新加坡
    - ap-southeast-2  #澳大利亚（悉尼）
    - ap-southeast-3  #马来西亚（吉隆坡）
    - ap-southeast-5  #印度尼西亚（雅加达）
    - eu-central-1  #德国（法兰克福）
    - eu-west-1 #英国（伦敦）
    - me-east-1 #阿联酋（迪拜）
    - us-east-1 #美国（弗吉尼亚）
    - us-west-1 #美国（硅谷）
