name: GitHub Actions Release
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        run: ./gradlew shadowJar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create GitHub release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          branch: main
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          automatic_release_tag: "latest"
          draft: false
          prerelease: false
          files: |
            libs/**.jar