name: Github Release
on:
  push:
    tags: # 提交代码为tag 是以'v'开头的时候触发自动部署到服务端 如 git push tag v0.1.0
      - 'v*'

jobs:
  build-release:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  build-linux-v17-temurin:
    runs-on: ubuntu-latest
    needs:
      - build-release
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2.3.1
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: java -version
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        run: ./gradlew shadowJar
      - name: Build Runtime
        run: $JAVA_HOME/bin/jlink --add-modules jdk.crypto.ec,java.base,java.compiler,java.logging,java.desktop,java.management,java.naming,java.net.http,java.rmi,java.scripting,java.security.jgss,java.sql,java.xml,jdk.jdi,jdk.unsupported --output ./runtime
      - name: Rename Jar
        run: mv ./build/libs/vertx-ddns-latest-all.jar ./build/libs/vertx-ddns.jar
      - name: Copy Jar
        run: cp ./build/libs/vertx-ddns.jar ./runtime/vertx-ddns.jar
      - name: Copy install.sh
        run: mv ./install.sh ./runtime
      - name: Copy uninstall.sh
        run: mv ./uninstall.sh ./runtime
      - name: Create Zip
        run: |
          zip -q -r runtime.zip ./runtime/*

      - name: Upload Release linux-runtime
        id: upload-release-linux-runtime
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ needs.build-release.outputs.upload_url }}
          asset_path: ./runtime.zip
          asset_name: runtime-17-temurin-linux.zip
          asset_content_type: application/zip
      - name: Upload Release jar
        id: upload-release-jar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ needs.build-release.outputs.upload_url }}
          asset_path: ./build/libs/vertx-ddns.jar
          asset_name: vertx-ddns-17-temurin.jar
          asset_content_type: application/jar

  build-linux-v16-openj9:
    runs-on: ubuntu-latest
    needs:
      - build-release
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt-openj9'
      - run: java -version
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        run: ./gradlew shadowJar
      - name: Build Runtime
        run: $JAVA_HOME/bin/jlink --add-modules jdk.crypto.ec,java.base,java.compiler,java.logging,java.desktop,java.management,java.naming,java.net.http,java.rmi,java.scripting,java.security.jgss,java.sql,java.xml,jdk.jdi,jdk.unsupported --output ./runtime
      - name: Rename Jar
        run: mv ./build/libs/vertx-ddns-latest-all.jar ./build/libs/vertx-ddns.jar
      - name: Copy Jar
        run: cp ./build/libs/vertx-ddns.jar ./runtime/vertx-ddns.jar
      - name: Copy install.sh
        run: mv ./install.sh ./runtime
      - name: Copy uninstall.sh
        run: mv ./uninstall.sh ./runtime
      - name: Create Zip
        run: |
          zip -q -r runtime.zip ./runtime/*
      - name: Upload Release linux-runtime
        id: upload-release-linux-runtime 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ needs.build-release.outputs.upload_url }}
          asset_path: ./runtime.zip
          asset_name: runtime-16-openj9-linux.zip
          asset_content_type: application/zip
      - name: Upload Release jar
        id: upload-release-jar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ needs.build-release.outputs.upload_url }}
          asset_path: ./build/libs/vertx-ddns.jar
          asset_name: vertx-ddns-16-openj9.jar
          asset_content_type: application/jar
